[package]
name = "healthcheck-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros", "uuid", "migrate"] }
uuid = { version = "1", features = ["v4"] }
dotenvy = "0.15"
reqwest = { version = "0.11", features = ["json", "gzip"] }
thiserror = "1"
tower = "0.4"
chrono = "0.4"
xlsxwriter = "0.6"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls", "uuid", "chrono"] }
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"


[build-dependencies]
sqlx = { version = "0.7", features = ["postgres", "macros"] }
